# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
# import libraries
import numpy as np
import pandas as pd

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import dataset
pokemon = pd.read_csv('pokemon.csv')
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

#### Print first 10 rows of `pokemon`.

In [3]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [7]:
# your code here
type_1 = pokemon['Type 1'].tolist()
type_2 = pokemon['Type 2'].tolist()
print(type_1)
print(type_2)

['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Poison', 'Poison', 'Electric', 'Electric', 'Ground', 'Ground', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy', 'Fire', 'Fire', 'Normal', 'Normal', 'Poison', 'Poison', 'Grass', 'Grass', 'Grass', 'Bug', 'Bug', 'Bug', 'Bug', 'Ground', 'Ground', 'Normal', 'Normal', 'Water', 'Water', 'Fighting', 'Fighting', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Fighting', 'Fighting', 'Fighting', 'Grass', 'Grass', 'Grass', 'Water', 'Water', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Electric', 'Electric', 'Normal', 'Normal', 'Normal', 'Water', 'Water', 'Poison', 'Poison', 'Water', 'Water', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Rock', 'Psychic', 'Psychic', 'Water', 'Water', 'Electric', 'Electric', 'Grass', 'Grass', 'Ground', 'Ground', 'Fighting', 'Fighting', 'Normal', 'Poison', 'Poison', 'Ground', 'Ground', 'Normal', 'Grass', 'Normal', 'Normal', 'Water', 'Water', 'Water', 'Water', 'Water', 'Water', 'Psychic', 'Bug', 'Ice', 'Electric', 'Fire', 'Bug', 'Bug', 'Normal', 'Water', 'Water', 'Water', 'Water', 'Normal', 'Normal', 'Water', 'Electric', 'Fire', 'Normal', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Rock', 'Normal', 'Ice', 'Electric', 'Fire', 'Dragon', 'Dragon', 'Dragon', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Bug', 'Bug', 'Bug', 'Bug', 'Poison', 'Water', 'Water', 'Electric', 'Fairy', 'Normal', 'Fairy', 'Fairy', 'Psychic', 'Psychic', 'Electric', 'Electric', 'Electric', 'Electric', 'Grass', 'Water', 'Water', 'Rock', 'Water', 'Grass', 'Grass', 'Grass', 'Normal', 'Grass', 'Grass', 'Bug', 'Water', 'Water', 'Psychic', 'Dark', 'Dark', 'Water', 'Ghost', 'Psychic', 'Psychic', 'Normal', 'Bug', 'Bug', 'Normal', 'Ground', 'Steel', 'Steel', 'Fairy', 'Fairy', 'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Dark', 'Normal', 'Normal', 'Fire', 'Fire', 'Ice', 'Ice', 'Water', 'Water', 'Water', 'Ice', 'Water', 'Steel', 'Dark', 'Dark', 'Dark', 'Water', 'Ground', 'Ground', 'Normal', 'Normal', 'Normal', 'Fighting', 'Fighting', 'Ice', 'Electric', 'Fire', 'Normal', 'Normal', 'Electric', 'Fire', 'Water', 'Rock', 'Rock', 'Rock', 'Rock', 'Psychic', 'Fire', 'Psychic', 'Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Water', 'Dark', 'Dark', 'Normal', 'Normal', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Water', 'Water', 'Water', 'Grass', 'Grass', 'Grass', 'Normal', 'Normal', 'Water', 'Water', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Bug', 'Bug', 'Grass', 'Grass', 'Normal', 'Normal', 'Normal', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Fighting', 'Fighting', 'Normal', 'Rock', 'Normal', 'Normal', 'Dark', 'Dark', 'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Fighting', 'Fighting', 'Fighting', 'Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Bug', 'Bug', 'Grass', 'Poison', 'Poison', 'Water', 'Water', 'Water', 'Water', 'Water', 'Fire', 'Fire', 'Fire', 'Fire', 'Psychic', 'Psychic', 'Normal', 'Ground', 'Ground', 'Ground', 'Grass', 'Grass', 'Normal', 'Dragon', 'Dragon', 'Normal', 'Poison', 'Rock', 'Rock', 'Water', 'Water', 'Water', 'Water', 'Ground', 'Ground', 'Rock', 'Rock', 'Rock', 'Rock', 'Water', 'Water', 'Normal', 'Normal', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Grass', 'Psychic', 'Dark', 'Dark', 'Psychic', 'Ice', 'Ice', 'Ice', 'Ice', 'Ice', 'Ice', 'Water', 'Water', 'Water', 'Water', 'Water', 'Dragon', 'Dragon', 'Dragon', 'Dragon', 'Steel', 'Steel', 'Steel', 'Steel', 'Rock', 'Ice', 'Steel', 'Dragon', 'Dragon', 'Dragon', 'Dragon', 'Water', 'Water', 'Ground', 'Ground', 'Dragon', 'Dragon', 'Steel', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Grass', 'Grass', 'Rock', 'Rock', 'Rock', 'Rock', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Water', 'Water', 'Grass', 'Grass', 'Water', 'Water', 'Normal', 'Ghost', 'Ghost', 'Normal', 'Normal', 'Normal', 'Ghost', 'Dark', 'Normal', 'Normal', 'Psychic', 'Poison', 'Poison', 'Steel', 'Steel', 'Rock', 'Psychic', 'Normal', 'Normal', 'Ghost', 'Dragon', 'Dragon', 'Dragon', 'Dragon', 'Normal', 'Fighting', 'Fighting', 'Fighting', 'Ground', 'Ground', 'Poison', 'Poison', 'Poison', 'Poison', 'Grass', 'Water', 'Water', 'Water', 'Grass', 'Grass', 'Grass', 'Dark', 'Electric', 'Normal', 'Ground', 'Grass', 'Electric', 'Fire', 'Fairy', 'Bug', 'Grass', 'Ice', 'Ground', 'Ice', 'Normal', 'Psychic', 'Psychic', 'Rock', 'Ghost', 'Ice', 'Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Psychic', 'Psychic', 'Psychic', 'Steel', 'Water', 'Fire', 'Normal', 'Ghost', 'Ghost', 'Psychic', 'Water', 'Water', 'Dark', 'Grass', 'Grass', 'Normal', 'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Dark', 'Dark', 'Grass', 'Grass', 'Fire', 'Fire', 'Water', 'Water', 'Psychic', 'Psychic', 'Normal', 'Normal', 'Normal', 'Electric', 'Electric', 'Rock', 'Rock', 'Rock', 'Psychic', 'Psychic', 'Ground', 'Ground', 'Normal', 'Normal', 'Fighting', 'Fighting', 'Fighting', 'Water', 'Water', 'Water', 'Fighting', 'Fighting', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Grass', 'Grass', 'Grass', 'Grass', 'Water', 'Ground', 'Ground', 'Ground', 'Fire', 'Fire', 'Fire', 'Grass', 'Bug', 'Bug', 'Dark', 'Dark', 'Psychic', 'Ghost', 'Ghost', 'Water', 'Water', 'Rock', 'Rock', 'Poison', 'Poison', 'Dark', 'Dark', 'Normal', 'Normal', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Water', 'Water', 'Ice', 'Ice', 'Ice', 'Normal', 'Normal', 'Electric', 'Bug', 'Bug', 'Grass', 'Grass', 'Water', 'Water', 'Water', 'Bug', 'Bug', 'Grass', 'Grass', 'Steel', 'Steel', 'Steel', 'Electric', 'Electric', 'Electric', 'Psychic', 'Psychic', 'Ghost', 'Ghost', 'Ghost', 'Dragon', 'Dragon', 'Dragon', 'Ice', 'Ice', 'Ice', 'Bug', 'Bug', 'Ground', 'Fighting', 'Fighting', 'Dragon', 'Ground', 'Ground', 'Dark', 'Dark', 'Normal', 'Normal', 'Normal', 'Dark', 'Dark', 'Fire', 'Bug', 'Dark', 'Dark', 'Dark', 'Bug', 'Bug', 'Steel', 'Rock', 'Grass', 'Flying', 'Flying', 'Electric', 'Electric', 'Dragon', 'Dragon', 'Ground', 'Ground', 'Dragon', 'Dragon', 'Dragon', 'Water', 'Water', 'Normal', 'Normal', 'Bug', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Fire', 'Fire', 'Bug', 'Bug', 'Bug', 'Fire', 'Fire', 'Fairy', 'Fairy', 'Fairy', 'Grass', 'Grass', 'Fighting', 'Fighting', 'Normal', 'Psychic', 'Psychic', 'Psychic', 'Steel', 'Steel', 'Steel', 'Steel', 'Fairy', 'Fairy', 'Fairy', 'Fairy', 'Dark', 'Dark', 'Rock', 'Rock', 'Poison', 'Poison', 'Water', 'Water', 'Electric', 'Electric', 'Rock', 'Rock', 'Rock', 'Rock', 'Fairy', 'Fighting', 'Electric', 'Rock', 'Dragon', 'Dragon', 'Dragon', 'Steel', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ice', 'Ice', 'Flying', 'Flying', 'Fairy', 'Dark', 'Dragon', 'Rock', 'Rock', 'Psychic', 'Psychic', 'Fire']
['Poison', 'Poison', 'Poison', 'Poison', nan, nan, 'Flying', 'Dragon', 'Flying', nan, nan, nan, nan, nan, nan, 'Flying', 'Poison', 'Poison', 'Poison', 'Poison', 'Flying', 'Flying', 'Flying', 'Flying', nan, nan, 'Flying', 'Flying', nan, nan, nan, nan, nan, nan, nan, nan, 'Ground', nan, nan, 'Ground', nan, nan, nan, nan, 'Fairy', 'Fairy', 'Flying', 'Flying', 'Poison', 'Poison', 'Poison', 'Grass', 'Grass', 'Poison', 'Poison', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Fighting', nan, nan, nan, nan, nan, nan, nan, 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Ground', 'Ground', 'Ground', nan, nan, 'Psychic', 'Psychic', 'Psychic', 'Steel', 'Steel', 'Flying', 'Flying', 'Flying', nan, 'Ice', nan, nan, nan, 'Ice', 'Poison', 'Poison', 'Poison', 'Poison', 'Ground', nan, nan, nan, nan, nan, nan, 'Psychic', 'Psychic', nan, nan, nan, nan, nan, nan, nan, 'Rock', 'Rock', nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Psychic', 'Fairy', 'Flying', 'Psychic', nan, nan, nan, 'Flying', nan, nan, 'Flying', 'Dark', 'Ice', nan, nan, nan, nan, nan, nan, 'Water', 'Water', 'Water', 'Water', 'Flying', 'Flying', nan, 'Flying', 'Flying', 'Flying', nan, nan, 'Flying', nan, 'Fighting', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Flying', 'Flying', 'Flying', 'Flying', 'Poison', 'Poison', 'Flying', 'Electric', 'Electric', nan, nan, 'Fairy', nan, 'Flying', 'Flying', 'Flying', nan, nan, nan, 'Dragon', nan, 'Fairy', 'Fairy', nan, nan, 'Flying', 'Flying', 'Flying', nan, nan, nan, 'Flying', 'Ground', 'Ground', nan, nan, 'Flying', 'Psychic', nan, nan, nan, 'Psychic', nan, 'Steel', nan, 'Flying', 'Ground', 'Ground', nan, nan, 'Poison', 'Steel', 'Steel', 'Rock', 'Fighting', 'Fighting', 'Ice', nan, nan, nan, 'Rock', 'Ground', 'Ground', 'Rock', nan, nan, 'Flying', 'Flying', 'Flying', 'Fire', 'Fire', 'Fire', 'Dragon', nan, nan, nan, nan, nan, nan, nan, 'Psychic', nan, nan, nan, nan, nan, nan, nan, 'Ground', 'Ground', 'Dark', 'Dark', 'Flying', 'Flying', 'Grass', nan, nan, nan, 'Dragon', nan, 'Fighting', 'Fighting', 'Fighting', nan, 'Ground', 'Ground', 'Ground', nan, nan, nan, nan, nan, nan, 'Flying', nan, 'Poison', 'Grass', 'Grass', 'Grass', nan, 'Dark', 'Dark', 'Flying', 'Flying', 'Flying', 'Flying', 'Fairy', 'Fairy', 'Fairy', 'Fairy', 'Water', 'Flying', nan, 'Fighting', nan, nan, nan, 'Ground', 'Flying', 'Ghost', nan, nan, nan, nan, nan, 'Fairy', nan, nan, nan, 'Ghost', 'Ghost', 'Fairy', 'Fairy', 'Rock', 'Rock', 'Rock', nan, 'Psychic', 'Psychic', 'Psychic', nan, nan, nan, nan, nan, nan, nan, 'Poison', nan, nan, 'Dark', 'Dark', 'Dark', nan, nan, 'Ground', 'Ground', 'Ground', nan, nan, nan, nan, nan, 'Dragon', 'Dragon', nan, 'Dark', 'Flying', 'Flying', 'Fairy', nan, nan, 'Psychic', 'Psychic', 'Ground', 'Ground', nan, 'Dark', 'Psychic', 'Psychic', 'Grass', 'Grass', 'Bug', 'Bug', nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Flying', nan, nan, nan, nan, nan, nan, nan, 'Water', 'Water', 'Water', nan, nan, nan, 'Rock', nan, nan, nan, 'Flying', 'Flying', 'Psychic', 'Psychic', 'Psychic', 'Psychic', nan, nan, nan, 'Psychic', 'Psychic', 'Psychic', 'Psychic', nan, nan, nan, 'Fire', 'Flying', 'Flying', 'Psychic', nan, nan, nan, nan, nan, nan, 'Ground', nan, 'Fighting', 'Fighting', nan, nan, 'Steel', 'Flying', 'Flying', 'Flying', nan, 'Water', nan, nan, nan, nan, nan, 'Poison', 'Poison', nan, nan, 'Steel', 'Steel', nan, 'Grass', 'Ground', 'Steel', 'Flying', 'Flying', 'Flying', nan, nan, nan, nan, nan, nan, 'Ground', nan, 'Flying', 'Flying', nan, nan, 'Fighting', nan, 'Flying', nan, nan, nan, 'Dark', 'Dark', 'Psychic', 'Psychic', nan, 'Fairy', nan, 'Flying', 'Dark', 'Ground', 'Ground', 'Ground', 'Ground', nan, nan, 'Steel', 'Steel', nan, nan, 'Bug', 'Dark', 'Fighting', 'Fighting', nan, nan, nan, 'Flying', 'Ice', 'Ice', 'Ice', 'Ice', 'Steel', nan, 'Rock', nan, nan, nan, 'Flying', 'Flying', nan, nan, 'Flying', 'Ground', nan, 'Fighting', 'Fighting', 'Steel', nan, 'Ghost', 'Ghost', 'Fire', 'Water', 'Ice', 'Flying', 'Grass', nan, nan, nan, 'Dragon', 'Dragon', 'Steel', nan, 'Dragon', 'Dragon', nan, nan, nan, nan, nan, 'Flying', nan, 'Fire', nan, nan, nan, nan, 'Fighting', 'Fighting', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Flying', 'Flying', 'Flying', nan, nan, nan, nan, nan, 'Flying', 'Flying', nan, 'Steel', nan, 'Fairy', nan, nan, nan, nan, 'Ground', 'Ground', nan, nan, 'Grass', 'Grass', 'Grass', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy', nan, nan, nan, 'Dark', 'Dark', 'Dark', nan, nan, 'Psychic', nan, 'Rock', 'Rock', 'Fighting', 'Fighting', 'Flying', nan, nan, 'Rock', 'Rock', 'Flying', 'Flying', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Flying', 'Flying', nan, nan, nan, 'Grass', 'Grass', 'Flying', nan, 'Steel', 'Poison', 'Poison', 'Ghost', 'Ghost', nan, 'Electric', 'Electric', 'Steel', 'Steel', nan, nan, nan, nan, nan, nan, nan, nan, 'Fire', 'Fire', 'Fire', nan, nan, nan, nan, nan, nan, nan, nan, 'Electric', nan, nan, nan, 'Ghost', 'Ghost', 'Steel', 'Steel', nan, 'Flying', 'Flying', 'Flying', 'Flying', nan, 'Steel', 'Dragon', 'Dragon', 'Dragon', 'Fire', 'Fire', 'Fighting', 'Fighting', 'Fighting', nan, nan, 'Flying', 'Flying', 'Fire', 'Electric', 'Flying', 'Flying', 'Ice', 'Ice', 'Ice', 'Fighting', 'Fighting', 'Psychic', 'Fighting', 'Steel', nan, nan, 'Fighting', nan, nan, 'Psychic', nan, nan, 'Dark', nan, 'Ground', 'Flying', 'Flying', 'Flying', nan, nan, 'Flying', 'Normal', 'Normal', nan, nan, nan, nan, nan, nan, 'Dark', nan, nan, nan, nan, 'Ghost', 'Ghost', 'Ghost', 'Ghost', nan, nan, nan, nan, 'Psychic', 'Psychic', 'Water', 'Water', 'Water', 'Dragon', nan, nan, 'Normal', 'Normal', 'Dragon', 'Dragon', 'Ice', 'Ice', nan, 'Flying', 'Fairy', 'Fairy', nan, nan, nan, 'Fairy', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', nan, nan, 'Dragon', 'Dragon', nan, 'Flying', 'Ground', 'Fairy', 'Fairy', 'Ghost', 'Dark', 'Water']

In [16]:
unique_types = pd.unique(pokemon[['Type 1', 'Type 2']].values.ravel('K'))
unique_types

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying', nan], dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [22]:
# your code here
pokemon['Name'].unique()
pokemon['Name'] = pokemon['Name'].str.replace(r'\w+Mega', 'Mega')


# test transformed data
pokemon.head(10)

C:\Users\Win10 Pro x64\AppData\Local\Temp\ipykernel_8768\2482591888.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  pokemon['Name'] = pokemon['Name'].str.replace(r'\w+Mega', 'Mega')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [25]:
# your code here
pokemon["A/D Ratio"] = pokemon['Attack'] / pokemon['Defense']

#### Identify the pokemon with the highest `A/D Ratio`.

In [34]:
# your code here
max_ratio_index = pokemon['A/D Ratio'].idxmax()
pokemon_ad_max = pokemon.loc[max_ratio_index, 'Name']
pokemon_ad_max

'DeoxysAttack Forme'

#### Identify the pokemon with the lowest A/D Ratio.

In [35]:
# your code here
min_ratio_index = pokemon['A/D Ratio'].idxmin()
pokemon_ad_min = pokemon.loc[min_ratio_index, 'Name']
pokemon_ad_min

'Shuckle'

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [38]:
# your code here
pokemon['Combo Type'] = pokemon['Type 1'] 
for index, row in pokemon.iterrows():
    if pd.notna(row['Type 2']):
        pokemon.at[index, 'Combo Type'] = f"{row['Type 1']}-{row['Type 2']}"

pokemon['Combo Type']

0       Grass-Poison
1       Grass-Poison
2       Grass-Poison
3       Grass-Poison
4               Fire
           ...
795       Rock-Fairy
796       Rock-Fairy
797    Psychic-Ghost
798     Psychic-Dark
799       Fire-Water
Name: Combo Type, Length: 800, dtype: object

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [89]:
# your code here
pokemon_sorted_adratio = pokemon.sort_values(by=['A/D Ratio'], ascending=False)
pokemon_sorted_adratio.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [93]:
# your code here
pokemon_sorted_adratio.reset_index(inplace=True) # run only once, How do we usually deal with lines of code that can be run only once?
cttop5_list = pokemon_sorted_adratio['Combo Type'].iloc[:5]
cttop5_list.to_list()
cttop5_list

0       Psychic
1    Water-Dark
2    Bug-Poison
3          Rock
4    Water-Dark
Name: Combo Type, dtype: object

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [94]:
# your code here
pokemon_sorted_adratio.set_index('Combo Type', inplace=True)
pivot=pokemon_sorted_adratio.select_dtypes(include='number').pivot_table(index=['Combo Type'])
pivot

,#,A/D Ratio,Attack,Defense,Generation,HP,Sp. Atk,Sp. Def,Speed,Total,index
Combo Type,,,,,,,,,,,
Bug,361.352941,0.940179,50.352941,55.411765,3.470588,53.058824,39.294118,43.647059,47.941176,289.705882,397.294118
Bug-Electric,595.500000,1.111667,62.000000,55.000000,5.000000,60.000000,77.000000,55.000000,86.500000,395.500000,656.500000
Bug-Fighting,214.000000,1.637681,155.000000,95.000000,2.000000,80.000000,40.000000,100.000000,80.000000,550.000000,231.500000
Bug-Fire,636.500000,1.234266,72.500000,60.000000,5.000000,70.000000,92.500000,80.000000,80.000000,455.000000,697.500000
Bug-Flying,286.285714,1.146274,70.142857,61.571429,2.857143,63.000000,72.857143,69.071429,82.857143,419.500000,314.571429
...,...,...,...,...,...,...,...,...,...,...,...
Water-Ice,103.000000,0.821759,83.333333,113.333333,1.000000,90.000000,80.000000,78.333333,66.666667,511.666667,111.333333
Water-Poison,118.666667,1.162149,68.333333,58.333333,1.333333,61.666667,61.666667,91.666667,85.000000,426.666667,128.000000
Water-Psychic,111.800000,0.783668,73.000000,104.000000,1.200000,87.000000,94.000000,79.000000,44.000000,481.000000,120.400000
Water-Rock,430.000000,0.727170,82.750000,112.750000,3.750000,70.750000,61.500000,65.000000,36.000000,428.750000,473.750000
Water-Steel,395.000000,0.977273,86.000000,88.000000,4.000000,84.000000,111.000000,101.000000,60.000000,530.000000,440.000000

In [95]:
pivot = pivot[pivot.index.isin(cttop5_list)]
pivot

,#,A/D Ratio,Attack,Defense,Generation,HP,Sp. Atk,Sp. Def,Speed,Total,index
Combo Type,,,,,,,,,,,
Bug-Poison,199.166667,1.315989,68.333333,58.083333,2.333333,53.750000,42.500000,59.333333,65.916667,347.916667,220.333333
Psychic,381.973684,1.164196,64.947368,67.236842,3.342105,72.552632,98.552632,82.394737,78.868421,464.552632,421.789474
Rock,410.111111,1.260091,103.333333,107.222222,3.888889,67.111111,40.555556,58.333333,32.888889,409.444444,453.555556
Water-Dark,347.666667,2.291949,120.000000,65.166667,3.166667,69.166667,88.833333,63.500000,87.166667,493.833333,380.833333